# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Constellation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Constellation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x43onstellation.proto\x1a\x19google/protobuf/any.proto\"\x1b\n\tIntVector\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x1e\n\x0cStringVector\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1d\n\x0b\x46loatVector\x12\x0e\n\x06values\x18\x01 \x03(\x01\"?\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x06values\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"\x8a\x01\n\nDataFormat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\nparameters\x18\x02 \x03(\x0b\x32\x1b.DataFormat.ParametersEntry\x1a=\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Parameter:\x02\x38\x01\"\xc1\x01\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\nparameters\x18\x02 \x03(\x0b\x32\x15.Node.ParametersEntry\x12\x1f\n\ninputTypes\x18\x03 \x03(\x0b\x32\x0b.DataFormat\x12 \n\x0boutputTypes\x18\x04 \x03(\x0b\x32\x0b.DataFormat\x1a=\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Parameter:\x02\x38\x01\"l\n\x04\x45\x64ge\x12\x13\n\x0binputNodeId\x18\x01 \x01(\x03\x12\x1b\n\x13inputParameterIndex\x18\x02 \x01(\x03\x12\x14\n\x0coutputNodeId\x18\x03 \x01(\x03\x12\x1c\n\x14outputParameterIndex\x18\x04 \x01(\x03\"\x90\x01\n\x0cProgramGraph\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05nodes\x18\x02 \x03(\x0b\x32\x18.ProgramGraph.NodesEntry\x12\x14\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\x05.Edge\x1a\x33\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Node:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_INTVECTOR = _descriptor.Descriptor(
  name='IntVector',
  full_name='IntVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='IntVector.values', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=77,
)


_STRINGVECTOR = _descriptor.Descriptor(
  name='StringVector',
  full_name='StringVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='StringVector.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=109,
)


_FLOATVECTOR = _descriptor.Descriptor(
  name='FloatVector',
  full_name='FloatVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='FloatVector.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=140,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='Parameter.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=205,
)


_DATAFORMAT_PARAMETERSENTRY = _descriptor.Descriptor(
  name='ParametersEntry',
  full_name='DataFormat.ParametersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataFormat.ParametersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataFormat.ParametersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=346,
)

_DATAFORMAT = _descriptor.Descriptor(
  name='DataFormat',
  full_name='DataFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DataFormat.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='DataFormat.parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAFORMAT_PARAMETERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=346,
)


_NODE_PARAMETERSENTRY = _descriptor.Descriptor(
  name='ParametersEntry',
  full_name='Node.ParametersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Node.ParametersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Node.ParametersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=346,
)

_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Node.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='Node.parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputTypes', full_name='Node.inputTypes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputTypes', full_name='Node.outputTypes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NODE_PARAMETERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=542,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputNodeId', full_name='Edge.inputNodeId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputParameterIndex', full_name='Edge.inputParameterIndex', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputNodeId', full_name='Edge.outputNodeId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputParameterIndex', full_name='Edge.outputParameterIndex', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=652,
)


_PROGRAMGRAPH_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='ProgramGraph.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ProgramGraph.NodesEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ProgramGraph.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=748,
  serialized_end=799,
)

_PROGRAMGRAPH = _descriptor.Descriptor(
  name='ProgramGraph',
  full_name='ProgramGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ProgramGraph.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='ProgramGraph.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='ProgramGraph.edges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROGRAMGRAPH_NODESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=799,
)

_PARAMETER.fields_by_name['values'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_DATAFORMAT_PARAMETERSENTRY.fields_by_name['value'].message_type = _PARAMETER
_DATAFORMAT_PARAMETERSENTRY.containing_type = _DATAFORMAT
_DATAFORMAT.fields_by_name['parameters'].message_type = _DATAFORMAT_PARAMETERSENTRY
_NODE_PARAMETERSENTRY.fields_by_name['value'].message_type = _PARAMETER
_NODE_PARAMETERSENTRY.containing_type = _NODE
_NODE.fields_by_name['parameters'].message_type = _NODE_PARAMETERSENTRY
_NODE.fields_by_name['inputTypes'].message_type = _DATAFORMAT
_NODE.fields_by_name['outputTypes'].message_type = _DATAFORMAT
_PROGRAMGRAPH_NODESENTRY.fields_by_name['value'].message_type = _NODE
_PROGRAMGRAPH_NODESENTRY.containing_type = _PROGRAMGRAPH
_PROGRAMGRAPH.fields_by_name['nodes'].message_type = _PROGRAMGRAPH_NODESENTRY
_PROGRAMGRAPH.fields_by_name['edges'].message_type = _EDGE
DESCRIPTOR.message_types_by_name['IntVector'] = _INTVECTOR
DESCRIPTOR.message_types_by_name['StringVector'] = _STRINGVECTOR
DESCRIPTOR.message_types_by_name['FloatVector'] = _FLOATVECTOR
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['DataFormat'] = _DATAFORMAT
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['ProgramGraph'] = _PROGRAMGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntVector = _reflection.GeneratedProtocolMessageType('IntVector', (_message.Message,), dict(
  DESCRIPTOR = _INTVECTOR,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:IntVector)
  ))
_sym_db.RegisterMessage(IntVector)

StringVector = _reflection.GeneratedProtocolMessageType('StringVector', (_message.Message,), dict(
  DESCRIPTOR = _STRINGVECTOR,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:StringVector)
  ))
_sym_db.RegisterMessage(StringVector)

FloatVector = _reflection.GeneratedProtocolMessageType('FloatVector', (_message.Message,), dict(
  DESCRIPTOR = _FLOATVECTOR,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:FloatVector)
  ))
_sym_db.RegisterMessage(FloatVector)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

DataFormat = _reflection.GeneratedProtocolMessageType('DataFormat', (_message.Message,), dict(

  ParametersEntry = _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAFORMAT_PARAMETERSENTRY,
    __module__ = 'Constellation_pb2'
    # @@protoc_insertion_point(class_scope:DataFormat.ParametersEntry)
    ))
  ,
  DESCRIPTOR = _DATAFORMAT,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:DataFormat)
  ))
_sym_db.RegisterMessage(DataFormat)
_sym_db.RegisterMessage(DataFormat.ParametersEntry)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(

  ParametersEntry = _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), dict(
    DESCRIPTOR = _NODE_PARAMETERSENTRY,
    __module__ = 'Constellation_pb2'
    # @@protoc_insertion_point(class_scope:Node.ParametersEntry)
    ))
  ,
  DESCRIPTOR = _NODE,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:Node)
  ))
_sym_db.RegisterMessage(Node)
_sym_db.RegisterMessage(Node.ParametersEntry)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), dict(
  DESCRIPTOR = _EDGE,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:Edge)
  ))
_sym_db.RegisterMessage(Edge)

ProgramGraph = _reflection.GeneratedProtocolMessageType('ProgramGraph', (_message.Message,), dict(

  NodesEntry = _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROGRAMGRAPH_NODESENTRY,
    __module__ = 'Constellation_pb2'
    # @@protoc_insertion_point(class_scope:ProgramGraph.NodesEntry)
    ))
  ,
  DESCRIPTOR = _PROGRAMGRAPH,
  __module__ = 'Constellation_pb2'
  # @@protoc_insertion_point(class_scope:ProgramGraph)
  ))
_sym_db.RegisterMessage(ProgramGraph)
_sym_db.RegisterMessage(ProgramGraph.NodesEntry)


_DATAFORMAT_PARAMETERSENTRY._options = None
_NODE_PARAMETERSENTRY._options = None
_PROGRAMGRAPH_NODESENTRY._options = None
# @@protoc_insertion_point(module_scope)
