# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestLatticeNetwork.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TestLatticeNetwork.proto',
  package='lattice',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18TestLatticeNetwork.proto\x12\x07lattice\"\xc7\x01\n\x0eLatticeNetwork\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x17\n\x0fnum_calibrators\x18\x02 \x02(\x05\x12\x14\n\x0cnum_lattices\x18\x03 \x02(\x05\x12\x14\n\x0clattice_size\x18\x04 \x02(\x05\x12\x14\n\x0clattice_rank\x18\x05 \x02(\x05\x12(\n\x0b\x63\x61librators\x18\x06 \x03(\x0b\x32\x13.lattice.Calibrator\x12\"\n\x08lattices\x18\x07 \x03(\x0b\x32\x10.lattice.Lattice\"6\n\nCalibrator\x12\x15\n\rnum_keypoints\x18\x01 \x02(\x05\x12\x11\n\tkeypoints\x18\x02 \x03(\x05\"1\n\x07Lattice\x12\x12\n\nnum_params\x18\x01 \x02(\x05\x12\x12\n\nparameters\x18\x02 \x03(\x05')
)




_LATTICENETWORK = _descriptor.Descriptor(
  name='LatticeNetwork',
  full_name='lattice.LatticeNetwork',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='lattice.LatticeNetwork.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_calibrators', full_name='lattice.LatticeNetwork.num_calibrators', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_lattices', full_name='lattice.LatticeNetwork.num_lattices', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattice_size', full_name='lattice.LatticeNetwork.lattice_size', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattice_rank', full_name='lattice.LatticeNetwork.lattice_rank', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calibrators', full_name='lattice.LatticeNetwork.calibrators', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lattices', full_name='lattice.LatticeNetwork.lattices', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=237,
)


_CALIBRATOR = _descriptor.Descriptor(
  name='Calibrator',
  full_name='lattice.Calibrator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_keypoints', full_name='lattice.Calibrator.num_keypoints', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keypoints', full_name='lattice.Calibrator.keypoints', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=293,
)


_LATTICE = _descriptor.Descriptor(
  name='Lattice',
  full_name='lattice.Lattice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_params', full_name='lattice.Lattice.num_params', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='lattice.Lattice.parameters', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=344,
)

_LATTICENETWORK.fields_by_name['calibrators'].message_type = _CALIBRATOR
_LATTICENETWORK.fields_by_name['lattices'].message_type = _LATTICE
DESCRIPTOR.message_types_by_name['LatticeNetwork'] = _LATTICENETWORK
DESCRIPTOR.message_types_by_name['Calibrator'] = _CALIBRATOR
DESCRIPTOR.message_types_by_name['Lattice'] = _LATTICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LatticeNetwork = _reflection.GeneratedProtocolMessageType('LatticeNetwork', (_message.Message,), dict(
  DESCRIPTOR = _LATTICENETWORK,
  __module__ = 'TestLatticeNetwork_pb2'
  # @@protoc_insertion_point(class_scope:lattice.LatticeNetwork)
  ))
_sym_db.RegisterMessage(LatticeNetwork)

Calibrator = _reflection.GeneratedProtocolMessageType('Calibrator', (_message.Message,), dict(
  DESCRIPTOR = _CALIBRATOR,
  __module__ = 'TestLatticeNetwork_pb2'
  # @@protoc_insertion_point(class_scope:lattice.Calibrator)
  ))
_sym_db.RegisterMessage(Calibrator)

Lattice = _reflection.GeneratedProtocolMessageType('Lattice', (_message.Message,), dict(
  DESCRIPTOR = _LATTICE,
  __module__ = 'TestLatticeNetwork_pb2'
  # @@protoc_insertion_point(class_scope:lattice.Lattice)
  ))
_sym_db.RegisterMessage(Lattice)


# @@protoc_insertion_point(module_scope)
